version: '3'

services:
  increment_service:
    image: lovro-docker
    build:
      context: .
      dockerfile: lovro-docker
    ports:
      - "5001:5000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis  # Use the service name as the hostname
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
